// Lista blanca de marcas permitidas (arreglo)
const ALLOWED_BRANDS = [

    "1g Gpt Profit",
    "1g Profit System",
    "1k D AIly Profit",
    "Accutrader 360",
    "Accutrader Alpha",
    "Accutrader Quantum",
    "Adept AI",
    "AI Aktienhandel",
    "AI Arbitrage",
    "AI Arbitrix",
    "AI Bizapp",
    "AI Definity 1000",
    "AI Definity Pro",
    "AI Genius Trading",
    "AI Growth Matrix",
    "AI Invest",
    "AI Investment",
    "AI Nigarity 1000",
    "AI Stock Profit",
    "AI Trader",
    "AI Trading",
    "Al Definity 1000",
    "Al Definity Pro",
    "Al Trader",
    "Alchemy Trade",
    "Algo Signals",
    "Algo Trader",
    "Alpha AI",
    "Altrex Edge",
    "Altrix Edge",
    "Altrix Sync",
    "Apex Capital AI",
    "Arbiquant",
    "Arbitrage Engine",
    "Arbivex",
    "Ascend Wealth",
    "Astral Edge",
    "Atom Finance",
    "Atomic Trade",
    "Aurora Wealth AI",
    "Axiom Trade",
    "Bgx AI",
    "Big Money Rush",
    "Biti App AI",
    "Bitzest Genius",
    "Bluequbit",
    "Börsengenien AI",
    "Botfinance Ia",
    "Capfund AI",
    "Capstone",
    "Cash Nest",
    "Crimson Flux AI",
    "Cryvon Wealth AI",
    "Cyber Stratus AI",
    "Easy Trade",
    "Echo Ki Trading",
    "Echo Prism",
    "Echo Prism AI",
    "Echo Trade",
    "Edgefinder Pro",
    "Engines Trader 1.9 Edge",
    "Etrader AI Gpt",
    "Everix Edge",
    "Everix Peak",
    "Evo Primex",
    "Exodus Trading",
    "Falconix Connect",
    "Falconix Matrix",
    "Fbc Algo",
    "Fbc Edge",
    "Finance Legend",
    "Finance Phantom",
    "Finance Profit Bot",
    "Finanzbot Ki",
    "Finotraze",
    "Fintrex Apex 2.7 AI",
    "Finvotrix",
    "Flick Edge",
    "Fluxquant",
    "Fortuixagent",
    "Fortune Maker Engine",
    "Fusion Immediate",
    "Fx Master Bot",
    "G AIn Generator Pro",
    "G AIn Mode AI",
    "G AInify AI",
    "Gas Forex",
    "Gas Profit",
    "Geldbot AI",
    "Geldrix Surge",
    "Gold Profit 24 AI",
    "Gold Scalping AI",
    "Golden Profit",
    "Golden Pulse AI",
    "Graminator",
    "Granimator",
    "Immediate 3.0",
    "Immediate Acceleration",
    "Immediate Access",
    "Immediate Ace",
    "Immediate Achieve",
    "Immediate Affinity",
    "Immediate AI",
    "Immediate Alora",
    "Immediate Alpha",
    "Immediate Apex",
    "Immediate App",
    "Immediate Aspect",
    "Immediate Axiom",
    "Immediate Beatwave",
    "Immediate Buz8z",
    "Immediate Capital",
    "Immediate Catalyst",
    "Immediate Charge",
    "Immediate Charm",
    "Immediate Code",
    "Immediate Connect",
    "Immediate Core",
    "Immediate Crest",
    "Immediate Dash",
    "Immediate Definity",
    "Immediate Denox",
    "Immediate Dex",
    "Immediate Dinero",
    "Immediate Dorut",
    "Immediate Earn",
    "Immediate Echelon",
    "Immediate Edge",
    "Immediate Elegance",
    "Immediate Elevation",
    "Immediate Energy",
    "Immediate Era",
    "Immediate Everix",
    "Immediate Evex",
    "Immediate Ewave",
    "Immediate Experience",
    "Immediate Export",
    "Immediate Fastx",
    "Immediate Flare",
    "Immediate Flex",
    "Immediate Flik",
    "Immediate Flow",
    "Immediate Fortune",
    "Immediate Future",
    "Immediate G AIns",
    "Immediate Gfund",
    "Immediate Glory",
    "Immediate Gof",
    "Immediate Gp",
    "Immediate Gpt",
    "Immediate Gran",
    "Immediate Granimator",
    "Immediate Grid",
    "Immediate Growth",
    "Immediate Hubu",
    "Immediate Income",
    "Immediate Infinity",
    "Immediate Innovault",
    "Immediate Intel Pro",
    "Immediate Investment",
    "Immediate Ipro",
    "Immediate Korb",
    "Immediate Kwave",
    "Immediate Lepon30",
    "Immediate Lexi",
    "Immediate Luminary",
    "Immediate Matrix",
    "Immediate Max AIr",
    "Immediate Maximum",
    "Immediate Method",
    "Immediate Migna",
    "Immediate Mix",
    "Immediate Momentum",
    "Immediate Motion",
    "Immediate Neon",
    "Immediate Neu Pro",
    "Immediate Nextgen",
    "Immediate Nexus",
    "Immediate Oil",
    "Immediate Optima",
    "Immediate Path",
    "Immediate Peak",
    "Immediate Plexmax",
    "Immediate Prime 3.7",
    "Immediate Prism",
    "Immediate Pro AIr",
    "Immediate Pro AIr",
    "Immediate Profit",
    "Immediate Pump",
    "Immediate R AIse",
    "Immediate Relative",
    "Immediate Rens",
    "Immediate Reo Pro",
    "Immediate Revolution",
    "Immediate Rex",
    "Immediate Rise",
    "Immediate Savage",
    "Immediate Script",
    "Immediate Smarter",
    "Immediate Solmar",
    "Immediate Spike",
    "Immediate Sprint",
    "Immediate Stratus AI",
    "Immediate Thorenext",
    "Immediate Trade",
    "Immediate Trend Pro",
    "Immediate Turbo",
    "Immediate Ucore",
    "Immediate Unity Profit",
    "Immediate Ursa",
    "Immediate Verde",
    "Immediate Visi70",
    "Immediate Vortex",
    "Immediate Wave",
    "Immediate Wealth",
    "Immediate Wortax",
    "Immediate X AI",
    "Immediate X3 Pro",
    "Immediate Xp",
    "Immediate Xport",
    "Immediate Xray",
    "Immediate Xrise",
    "Immediate Xtrade",
    "Immediate Zenith",
    "Immediate Zenx",
    "Immutable Dynamix",
    "Impulso Immediato",
    "Innova Trader AI",
    "Innova Trading",
    "Insta Corvex",
    "Insta Corvex AI",
    "Instan Max AI",
    "Instant Boost AI",
    "Instant Kline",
    "Instant Kline AI",
    "Instant Max",
    "Instant Max AI",
    "Instant Profit",
    "Instant Sform",
    "Instant Vortex AI",
    "Instant Xplan",
    "Instant Xplan AI",
    "Invest Gpt",
    "Invest Wave Max",
    "Investcan",
    "Investimal AI",
    "Kapitalwelle AI",
    "Ki Börsenhandel",
    "Ki Profit",
    "Ki Quant",
    "Ki Trading",
    "Kraditex",
    "Kwantix AI",
    "Lomarvixpro",
    "Loonietrade AI Pro",
    "Lucrosa Infinity",
    "Lucrosa Trade",
    "Lumina Crest AI",
    "Luxe Verse AI",
    "Luxitrade 99 AI",
    "Luxver Blitz AI",
    "Lynexistrader 9.3 Flex",
    "Magnum Trade",
    "Manara AI",
    "Marvex Trader 7.2 Core",
    "Matrixator",
    "Metaset AI",
    "Mindtrade AI",
    "Mobius Trader 7",
    "Momentum Glow",
    "Momentum Glow AI",
    "Nearest Edge",
    "Nebula Wealth",
    "Nelavor Trader 9.6 AI",
    "Neura Trade",
    "Neurix Profit",
    "Nexaveropro",
    "Nexmist Axiom AI",
    "Nexonix Profit",
    "Nextgenstocks AI",
    "Norvexiopro",
    "Novarix Trader 3.9 Flex",
    "Nwealth",
    "Oil Evex",
    "Oil Flex",
    "Oil Profit",
    "Oil Trade",
    "Öl Profit",
    "Optima Cortex",
    "Orion Edge AI",
    "Orion Hedge",
    "Oryvian",
    "Pandora Profit AI",
    "Pantera Edge",
    "Paragonix Edge",
    "Power Trades",
    "Proficator",
    "Profit Builder",
    "Profit Edge",
    "Profit Max",
    "Profit Maximizer",
    "Profit Method",
    "Profit Phantom",
    "Profit Revolution",
    "Profit Rex",
    "Profit Secret",
    "Profit Trader",
    "Profitrexor AI",
    "Profitsmaks",
    "Profixbot",
    "Prosignals AI",
    "Pure Point Profit",
    "Quant AI",
    "Quant X",
    "Quantalys AI",
    "Quantix Prime AI",
    "Quantum AI",
    "Quantum Apex",
    "Quantum Edge",
    "Quantum Extra Income",
    "Quantum Financial System",
    "Quantum Flash",
    "Quantum G Force",
    "Quantum Genius",
    "Quantum Gforce",
    "Quantum Hancock",
    "Quantum Max AIr",
    "Quantum Neural",
    "Quantum Prime AI",
    "Quantum Prime Profit",
    "Quantum Revolution",
    "Quantum Verse AI",
    "Quantum Xboom",
    "Quantum Xrift",
    "Quantumx",
    "Quebex Wealth",
    "Qumas AI",
    "Quopi AI",
    "Quotex Profit",
    "Rise Profit Fx",
    "Robbo AI",
    "Robospark Investor",
    "Rockflow AI",
    "Selvion Platform",
    "Senerwind",
    "Sentiotrade",
    "Smart Method AI",
    "Smart Money AI",
    "Smart Profit AI",
    "Smart Stock AI",
    "Smart Trader",
    "Solid Return",
    "Solvex Trader 1.7",
    "Sqm Profit",
    "Stable Capital Pro",
    "Stable Index Profit",
    "Steel Wealth",
    "Stocks Synergy AI",
    "Stormg AIn",
    "Super Trader",
    "Swap 2.0 App",
    "Swap Max AIr",
    "Swap Pro AIr",
    "Syntek AI",
    "Tesler",
    "Tesler Infinity",
    "Tgx AI",
    "The News Spy",
    "Titanium AI",
    "Trade 2.0 Vedex",
    "Trade 350 App",
    "Trade 500 App",
    "Trade Actions",
    "Trade Actions 7.3 AI",
    "Trade Alora",
    "Trade Connect AI",
    "Trade Definity",
    "Trade Edge",
    "Trade Elians",
    "Trade Exit",
    "Trade Flex",
    "Trade Force",
    "Trade Fuse AI",
    "Trade Gpt",
    "Trade Gpt Force",
    "Trade Hero",
    "Trade Liberte AI",
    "Trade Like Crazy AI",
    "Trade Lindex AI",
    "Trade Liv49",
    "Trade Max AI",
    "Trade Max AIr",
    "Trade Neu Pro",
    "Trade Nexus",
    "Trade Pro AIr",
    "Trade Quest",
    "Trade Reo Pro",
    "Trade Spark",
    "Trade Spark 72 AI",
    "Trade Vanta",
    "Trade Vanta 4.1 AI",
    "Trade Vantix",
    "Trade Vector AI",
    "Trade Vista X",
    "Trade Vista X 4.7 Gpt AI",
    "Trade Vista X 7.1",
    "Trade Vortex",
    "Trade Wave",
    "Trade Zend",
    "Tradeelinas",
    "Tradeelinas 7.2 AI",
    "Tradeflex",
    "Tradelab AI",
    "Tradelunexfin",
    "Trademintus 8.1 AI",
    "Tradenex Maven",
    "Tradenexus",
    "Tradenexus 9.3 Gpt",
    "Tradenix AI",
    "Trader AI",
    "Trader Bolt 3.1",
    "Trader Bot",
    "Trader Flix Gpt",
    "Trader Intel AI",
    "Trader Mate",
    "Trader Pro AIr",
    "Trader Pro AIr AI",
    "Trader Profit",
    "Traderflix 9 Gpt",
    "Traderhive",
    "Traderhive 4.2 AI",
    "Traderrapide Ia",
    "Traders Edge",
    "Tradesen AI 82 Gpt",
    "Tradespark",
    "Tradespark 72 AI",
    "Tradesynth",
    "Tradevistax",
    "Tradevistax 1.4 AI",
    "Tradevistax 4.7 Gpt AI",
    "Tradevistax 7.1 Gpt",
    "Tradevistax Gpt AI",
    "Tradewiz Bot",
    "Tradexprofit",
    "Tradezend",
    "Tradezend 9.1 Gpt AI",
    "Trading Hero",
    "Trading Minus",
    "Trading Minus 8.1 AI",
    "Trading Signals AI",
    "Trendfind AI",
    "Trendspider AI",
    "Trilox AI",
    "Turbotrader 3.9 AI",
    "Ultimate Fund 1000",
    "Value Zone AI",
    "Vanado Trade",
    "Veltrix AI",
    "Veltrixfin",
    "Velyra Platform",
    "Veridian Matrix AI",
    "Voltix Edge",
    "Voltix Momentum",
    "Vortex Echo AI",
    "Vortex Genesis",
    "Vortex Genesis AI",
    "Vortex Momentum",
    "Wealth Catalyst",
    "Wealth Forge AI",
    "Wealth Matrix",
    "Wealth Phantom",
    "Wealthy Digital",
    "Wealthy G AIner",
    "X1 Algo",
    "Xenovix Trader 6.3 Edge",
    "Xtraderamg",
    "Xyberito Acoes AI",
    "Yuan International",
    "Yuan International AI",
    "Yuan Pay Group",
    "Yuan Profit",
    "Zavonix Trader 7.1",
    "Zelvionx",
    "Zentrix Trader 2.8 Fusion",
    "Zolavextrader",
    "AI Ch AIn Trader",
    "AI Nigarity",
    "AIvora Trade",
    "Anon System",
    "Arcane Trade",
    "Argentis Grid Gpt",
    "Biffy AI",
    "Binawex",
    "Bit 360 AI",
    "Bit AI App",
    "Bit AI Method",
    "Bit App 24",
    "Bit Evex",
    "Bit Gpt App",
    "Bit Index AI",
    "Bit Max AIr",
    "Bitalpha AI",
    "Bitamg 3.0 AI Nedir",
    "Bitamg 450 Algo",
    "Bitamg AI",
    "Bitamg Algo",
    "Bitamg Force",
    "Bitamg Plixi",
    "Bitbinvest",
    "Bitflex Gpt",
    "Bithq",
    "Bithq Matrix",
    "Biticodes",
    "Bitiq",
    "Bitlax Lab AI",
    "Bitlax Smart",
    "Bitlq",
    "Bitlq Matrix",
    "Bitplex",
    "Bitpro Trading",
    "Bitprofit",
    "Bitqs",
    "Bitqt",
    "Bitsgap",
    "Bitsignals",
    "Bitsoft 360",
    "Bittrader",
    "Bittrady",
    "Bitvavo AI",
    "Bitvestment",
    "Bitwave Reaction AI",
    "Brontivex",
    "Cancentra AI",
    "Ch AIn Reaction",
    "Coin Trade",
    "Coinsterix",
    "Cryptex AI",
    "Crystria Trading Bot",
    "Dexiaro Trade",
    "Dexiaro Trade 1.2 AI",
    "Drexiron Flow AI",
    "Ethamg",
    "Ethamg 2.6 AI",
    "Ethereon Edge",
    "G AIngate",
    "Gas Evex",
    "Gpt Affinity",
    "Gpt Definity",
    "Gpt Trading",
    "Grok Trading Bot",
    "Growbot Trading",
    "Immediate Bitnex",
    "Immediate Bitwave",
    "Immediate Byte",
    "Immediate Ch AIn",
    "Immediate Codex",
    "Immediate Coraldex",
    "Immediate Enigma",
    "Immediate Exgen",
    "Immediate Robbo",
    "Immediate T6 Avenium",
    "Immediate Xenon30",
    "Immediate Xgen",
    "Immediate Xzen",
    "Immediate Zcash",
    "Immutable Corvex",
    "Immutable Evex",
    "Imperial Go",
    "Kradivex",
    "Libra Method",
    "Lucrabot Gpt",
    "Neoprofit",
    "Netherexpro",
    "Oximarn Bot 7.1",
    "Paragonix Earn",
    "Ponte Quantum",
    "Prime Aurora",
    "Quantum Assets AI",
    "Quantum Bitqz",
    "Quantum Capital",
    "Quantum Code",
    "Quantum Core",
    "Quantum Dexion",
    "Quantum Fbc",
    "Quantum Gpeak",
    "Quantum Growth",
    "Quantum Income",
    "Quantum Morph AI",
    "Quantum Neura",
    "Quantum Plattform",
    "Quantum Trust",
    "Quantumneura",
    "Quantumneural",
    "Quantumorph AI",
    "Quantunix AI",
    "Rynox Vault",
    "Smart Bit Formula",
    "Smartbit Boost",
    "Sovonex Trader 1.9 Edge",
    "Sovrex Trader",
    "Stormcoin",
    "Synex Trade AI",
    "Syntrocoin",
    "Tokenizer 360",
    "Toravex Trader",
    "Trade Apex",
    "Trade Elians 7.2 AI",
    "Trade Gpt Plixi",
    "Trade Nexus 9.3 Gpt",
    "Trade Plixi",
    "Trade Zend 9.1 Gpt",
    "Trademintus",
    "Trader Talonix",
    "Trader Talonix 8.5 AI",
    "Ultra Swap AI",
    "Xbt 360 AI",
    "Xbt Evex",
    "Xbt Pro AIr",
    "Yuan Prime",
    "Zyntrax Vault",
    "1000 Coin Ifex",
    "AI Avapro Trading",
    "AI Bot Iplex",
    "AI Pro Iplex",
    "Bit Avage",
    "Bit Eprex",
    "Bit Iplex",
    "Bit Lidex",
    "Bit Sprix",
    "Bit Urex",
    "Biti Iplex",
    "Coin Ifex",
    "Coin Trade Capex",
    "Coin Trade Ifex",
    "Gas Alrex",
    "Gas Eprex",
    "Gas Folex",
    "Gpt Eurax",
    "Gpt Ifex",
    "Gpt Serax",
    "Gpt Urex",
    "Immediate Alrex",
    "Immediate Atarax",
    "Immediate Avage",
    "Immediate Avapro",
    "Immediate Avita",
    "Immediate Avonex",
    "Immediate Bumex",
    "Immediate Capex",
    "Immediate Chantix",
    "Immediate Chenix",
    "Immediate Cipro",
    "Immediate Dex AIr",
    "Immediate Duac",
    "Immediate Eprex",
    "Immediate Eurax",
    "Immediate Evista",
    "Immediate Exalgo",
    "Immediate Flarex",
    "Immediate Folex",
    "Immediate Hiprex",
    "Immediate Ifex",
    "Immediate Imovax",
    "Immediate Intal",
    "Immediate Iplex",
    "Immediate Keflex",
    "Immediate Lidex",
    "Immediate Lotemax",
    "Immediate Mentax",
    "Immediate Olux",
    "Immediate Relpax",
    "Immediate Serax",
    "Immediate Sprix",
    "Immediate Urex",
    "Immediate Wise",
    "Imperial Oil",
    "Instant Cormax",
    "Iplex Profit",
    "Neuro Trader",
    "Oil Eprex",
    "Oil Folex",
    "Oil Iplex",
    "Oil Lidex",
    "Petrol Eprex",
    "Petrol Intal",
    "Quantum Alrex",
    "Quantum Arava",
    "Quantum Bumex",
    "Quantum Dex AIr",
    "Quantum Edex",
    "Quantum Ifex",
    "Quantum Lexapro",
    "Quantum Medrol",
    "Sofortiges Xibrom",
    "Swap Alrex",
    "Trade Alrex",
    "Trade Avapro",
    "Trade Avita",
    "Trade Bumex",
    "Trade Capex",
    "Trade Cipro",
    "Trade Dex AIr",
    "Trade Duac",
    "Trade Eprex",
    "Trade Eurax",
    "Trade Evista",
    "Trade Flarex",
    "Trade Folex",
    "Trade Intal",
    "Trade Iplex",
    "Trade Lidex",
    "Trade Serax",
    "Trade Sprix",
    "Trade Urex",
    "Trader Lexipro AI"
];

// Valor por defecto (puede ser el primero u otro)
const DEFAULT_BRAND = "Immediate Edge";